### ISSUE TITLE
Font tip

### ISSUE THREAD

**Issue by Akikosophia** [Daan645/the-startup-responsive-interactieve-website#3]
https://www.cdnfonts.com/gilroy-bold.font

Deze font kun je gebruiken!

**Comment by Daan645** [comment]
Goede tip heb het geimplementeerd!
@import url('https://fonts.cdnfonts.com/css/gilroy-bold');

**Comment by Daan645** [comment]
Goede tip heb het geimplementeerd!
https://github.com/import url('https://fonts.cdnfonts.com/css/gilroy-bold');
