### ISSUE TITLE
CSS :DRY

### ISSUE THREAD

**Issue by Akikosophia** [Daan645/the-startup-responsive-interactieve-website#4]
In je CSS kun je DRY toepassen

De h1,h2,h3 kun je ook op 1 regel zetten. :)

**Comment by Akikosophia** [comment]
De code die je hebt kun je op 1 regel zetten zodat je minder code hoeft te schrijven

**Comment by Daan645** [comment]
Bedankt voor de tip heb het toegevoegd aan mijn code!

/*text properties*/
h1 h2 h3 p {
    font-family: var(--textFont);
    max-width: 60ch;
}

h1, h2, h3 {
    line-height: 1.2; /* of line-height: 1.2em; */
    letter-spacing: 0.05em;
    font-weight: bold;
}

**Comment by KoopReynders** [comment]
check dit:
```<html>```
