### ISSUE TITLE
HTML Validator: ```<alt>``` attribuut op ```<img>```

### ISSUE THREAD

**Issue by Annevd** [Daan645/the-startup-responsive-interactieve-website#7]
![image](https://github.com/Daan645/the-startup-responsive-interactieve-website/assets/144004647/45d6be41-894e-4815-a009-e19f1c679b23)

Je hebt nu meerdere  ```<img>``` elementen zonder ```<alt>``` attribuut. 
Deze  ```<img>``` elementen zou je nog kunnen aanvullen door ze een alternatieve tekst te geven. Als het geen alt tekst nodig is kan je hem leeg laten: ```<alt="">```

Lees hier meer over alt teksten bij images:
https://www.w3schools.com/tags/att_img_alt.asp

**Comment by Daan645** [comment]
Heb er een alt bij gezet bedankt voor de tip!
