### ISSUE TITLE
HTML Validator: section lacks heading

### ISSUE THREAD

**Issue by Annevd** [Daan645/the-startup-responsive-interactieve-website#8]
![image](https://github.com/Daan645/the-startup-responsive-interactieve-website/assets/144004647/e15f9894-a21b-48af-9331-fa859b10e2ba)
https://github.com/Daan645/the-startup-responsive-interactieve-website/blob/48bdbbee5a6f41a775488e28bb37b1d4412ead7d/index.html#L49-L65

Je hebt hier een section in een section. Bij sections is het gebruikelijk om een heading te hebben van h2-h6, in de binnenste section zit dit wel.
Misschien kan je de buitenste section in een div veranderen.

Hier kan je meer lezen over het section element en uitzonderingen van sections zonder heading:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#using_a_section_without_a_heading

**Comment by Daan645** [comment]
opgelost heb er een div van gemaakt!
